### ISSUE TITLE
Break out logo to package

### ISSUE THREAD

**Issue by avaer** [webaverse/dashboard#11]
The logos floating in the scene (W and Webaverse) are currently in this top-level repo. They could be broken out into a separate editable package, rather than having top-level scene content that is different from the rest of the code.

https://github.com/webaverse/webaverse/blob/824dc9702527027a22a54aef4908c0f6a14ef40f/app.js#L58

**Comment by shu8** [comment]
I was just having a look at this - am I right in saying that the logo package(s) that we make should have the floating/bouncing animation contained within themselves too, rather than it being done in the code using the animation loop? (like your [ocean package](https://github.com/avaer/ocean) currently has the rippling effect 'built in' to it?)

**Comment by avaer** [comment]
There are two ways to do it -- one would be to bake such an animation in blender and then just e.g. load the package as a `gltf` type -- and the other is to extract out the THREE.js code into a package.

The second is probably easier and more editable.

But the main point of this issue is to not have a "bare" render loop in the top site, but to showcase that everything is just a package. The fact that the logos don't follow this is an oversight.
